services:
  - type: web
    name: Personal_Portfolio-server
    env: docker
    repo: https://github.com/KuroiAkuma19/Personal_Portfolio.git
    branch: main
    dockerfilePath: server/Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ALLOWED_HOSTS
        value: Personal-Portfolio-server.onrender.com
        sync: false
